title: Hiro Ito # your name (or website title) here
logo: "/images/hiro_ito.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>Data Analyst & Frontend developer</p>
  <p>Three years of combined experience analysing online behaviour and business processes with track record of high impact insights produced.</p>
  <p>Expertise in SQL, as well as behaviour analytics and optimisation tools from Adobe and Google, working knowledge of Python.</p>
  <p>Strong internal and external stakeholder management.</p>
  <p><a href="https://www.linkedin.com/in/hiroakiito/">View My LinkedIn Profile</a></p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
